### ISSUE TITLE
im getting an error everytime i try to use /imagine

### ISSUE THREAD

**Issue by kroryan** [AndBobsYourUncle/stable-diffusion-discord-bot#44]
so any time i use /imagine this happend:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x446fc4]

goroutine 52 [running]:
stable_diffusion_bot/discord_bot.(*botImpl).processImagineCommand(0x40003d6180, 0x4000125880?, 0x4000010038)
        /home/pi/stable-diffusion-discord-bot/discord_bot/discord_bot.go:402 +0x354
stable_diffusion_bot/discord_bot.New.func2(0x4000125880?, 0x4000010038)
        /home/pi/stable-diffusion-discord-bot/discord_bot/discord_bot.go:104 +0x328
github.com/bwmarrin/discordgo.interactionCreateEventHandler.Handle(0x0?, 0x0?, {0x4a9940?, 0x4000010038?})
        /home/pi/go/pkg/mod/github.com/bwmarrin/discordgo@v0.26.3/eventhandlers.go:693 +0x44
created by github.com/bwmarrin/discordgo.(*Session).handle
        /home/pi/go/pkg/mod/github.com/bwmarrin/discordgo@v0.26.3/event.go:171 +0x15c

**Comment by kroryan** [comment]
it is solve now im trying to figure out how to change the steps 80 steps would take 2 hours for me....
